// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://htbulxccoeshqusytmdi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0YnVseGNjb2VzaHF1c3l0bWRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4NzcwMzQsImV4cCI6MjA2MjQ1MzAzNH0.ElZR6FTEkPYTRYtChg7s33dbPLY80SN3jpezB_skoto";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);